JIT insert of shader dictionary
hoverinc/three.js pull request #1
Opened 2017-05-23 18:33 UTC by jayhover

2017-05-23 18:36 UTC, jayhover commented
replace the hardcoded dj2?

2017-05-24 21:10 UTC, elfrank commented
@jayhover how to run build?
`npm run build-uglify`

Reference: https://github.com/mrdoob/three.js/wiki/Build-instructions

2017-05-24 21:15 UTC, elfrank requested changes

2017-05-24 21:15 UTC, elfrank commented on build/three.js
> +	    for (i = 0; i < str.length; i++) {
@jayhover `i` is not defined

2017-05-24 21:16 UTC, elfrank commented
@jayhover after your fix, remember to run `npm run build-uglify` and push the build changes as well.

2017-05-24 22:48 UTC, jayhover commented on build/three.js
> +	    for (i = 0; i < str.length; i++) {
err I thought I fixed that... hmm

2017-05-24 23:21 UTC, jayhover commented
pushed ( uglified )

2017-05-25 03:30 UTC, elfrank requested changes

2017-05-25 03:30 UTC, elfrank commented on build/three.js
> +	        char = str.charCodeAt(i);
@jayhover `char` not defined

2017-05-30 22:24 UTC, jayhover commented
just pushed a few more flags to provide mode perf info.

2017-06-01 21:54 UTC, elfrank requested changes

2017-06-01 21:54 UTC, elfrank commented on src/renderers/webgl/WebGLProgram.js
> +        char = str.charCodeAt(i);
@jayhover `char` is not defined

2017-06-01 22:45 UTC, closed without merging